// import { DM_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { ThemeProvider } from "./lib/context/ThemeProvider";
import { ThemeContextProvider } from "./lib/context/ThemeContext";

// const dmSans = DM_Sans({
//   subsets: ["latin"],
//   display: "swap",
// });

export const metadata = {
  title: "AI Content Studio",
  description: "Generated by create AI Content Studio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <Providers>
            <ThemeContextProvider>{children}</ThemeContextProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
