import { DM_Sans } from "@next/font/google";
import "./globals.css";
import Providers from "./providers";
import { ThemeProvider } from "./_components/ThemeProvider";
import { ThemeContextProvider } from "./_components/ThemeContext";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "AI Content Studio",
  description: "Generated by create AI Content Studio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={dmSans.className}>
        <ThemeProvider>
          <Providers>
            <ThemeContextProvider>{children}</ThemeContextProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
