export const mockVersions = [
  {
    id: "v1",
    documentId: "doc-1",
    content: "This is the first draft...",
    source: "user",
    createdAt: "2024-01-01",
  },
  {
    id: "v2",
    documentId: "doc-1",
    content: "This is the improved version generated by AI.",
    source: "ai",
    createdAt: "2024-01-02",
  },
];

export function getLatestVersion(documentId) {
  const versions = mockVersions
    .filter((v) => v.documentId === documentId)
    .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));

  return versions[0] || null;
}
